timezone: America/Los_Angeles
url: https://creatorcapital.cc
site_name: creatorcapital.cc
permalink: /posts/:title/
google_analytics_account: "UA-70432631-4"
twitter_username: lessin
plugins_dir: ./_plugins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
highligher: pygments
